### ISSUE TITLE
Unable to upload photos, install updates due to permission issue

### ISSUE THREAD

**Issue by firozxpd** [bitnami/bitnami-docker-aws-cli#6]
### Name and Version

WordPress 5.9.3

### What steps will reproduce the bug?

Login to the wordpress admin
Go to posts
Create a post
Add an image
upload an image - Not working due to permission issue

OR

Try install update of the wordpress or any other plugins - also not happening due to the permission issue.

### What is the expected behavior?

Set the folder permission 755 for all folders and sub folders under "wp-content"
Set the folder permission 644 for all files recursively in the "wp-content"

Expected to work as normal according the WordPress

### What do you see instead?

Not able to upload files
Not able to install updates

### Additional information

I set permission for the folders using chmod commadn
cd /bitnami/wordpress
chmod 755 wp-content/* -R
chmod 644 wp-content/*.* -R

Looking forward to a quick response because it is production!

**Comment by carrodher** [comment]
Hi, I'm closing this ticket as duplicated of https://github.com/bitnami/charts/issues/9766
